name: some_calendar
description: Custom calendar (multi select, single select, date range) for Flutter
version: 2.0.0
authors:
  - Irvan Lutfi Gunawan <irvan.devv17@gmail.com>
  - Garrett Barlocker <garrett@approachablegeek.com>
homepage: https://github.com/approachableGeek/some-calendar.git
license: MIT

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jiffy: ^4.1.0
  intl: ^0.17.0
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: roboto-regular
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
    - family: playfair-regular
      fonts:
        - asset: fonts/playfair.ttf
